# Generated by Django 6.0.6 on 2026-06-21 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('college_code', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('college_code', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('internal', models.CharField(max_length=50)),
                ('assignment_marks', models.IntegerField(blank=True, null=True)),
                ('exam_marks', models.IntegerField(blank=True, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aims.student')),
            ],
        ),
    ]
